/**
 * Tamil UI text in everyday spoken style (பேச்சு மொழி) — the way people talk at home and how popular
 * Tamil apps read: friendly "-ங்க" endings and common English words people already use (கிச்சன், ரெசிபி, லாகின்).
 * Keys are the English strings used in t('…'). Keep {placeholders} unchanged.
 */
const ta: Record<string, string> = {
  // Navigation & common
  Home: 'ஹோம்',
  Kitchen: 'கிச்சன்',
  Cook: 'சமைக்க',
  Planner: 'பிளான்',
  Groceries: 'மளிகை',
  AI: 'AI',
  Profile: 'ப்ரொஃபைல்',
  'Adupangarai home': 'அடுப்பங்கரை ஹோம்',
  Back: 'பின்னாடி',
  Cancel: 'வேண்டாம்',
  Close: 'மூடு',
  Save: 'சேவ் பண்ணு',
  'Save changes': 'சேவ் பண்ணு',
  Edit: 'மாத்து',
  Delete: 'டெலீட்',
  Remove: 'எடுத்துடு',
  Change: 'மாத்து',
  Add: 'சேர்',
  New: 'புதுசு',
  Review: 'பாருங்க',
  OK: 'சரி',
  All: 'எல்லாம்',
  More: 'கூட்டு',
  Fewer: 'குறை',
  Optional: 'தேவைப்பட்டா',
  optional: 'தேவைப்பட்டா',
  Name: 'பேர்',
  Email: 'இமெயில்',
  Password: 'பாஸ்வேர்ட்',
  Language: 'மொழி',
  Today: 'இன்னைக்கு',
  today: 'இன்னைக்கு',
  tomorrow: 'நாளைக்கு',
  '…': '…',
  'Loading…': 'லோட் ஆகுது…',
  'Please wait…': 'கொஞ்சம் வெயிட் பண்ணுங்க…',
  'Something went wrong': 'ஏதோ தப்பா போச்சு',
  'Something went wrong.': 'ஏதோ தப்பா போச்சு.',
  'Try again': 'திரும்ப ட்ரை பண்ணுங்க',
  'Could not reach the server. Check your connection.': 'சர்வர் கிடைக்கல. இன்டர்நெட் கனெக்‌ஷனை செக் பண்ணுங்க.',

  // Meals, places, units
  breakfast: 'காலை டிபன்',
  lunch: 'மதியம் சாப்பாடு',
  snack: 'ஸ்நாக்ஸ்',
  dinner: 'ராத்திரி சாப்பாடு',
  Breakfast: 'காலை டிபன்',
  Lunch: 'மதியம் சாப்பாடு',
  Snack: 'ஸ்நாக்ஸ்',
  Dinner: 'ராத்திரி சாப்பாடு',
  pantry: 'அலமாரி',
  fridge: 'ஃப்ரிட்ஜ்',
  freezer: 'ஃப்ரீசர்',
  piece: 'எண்ணம்',
  packet: 'பாக்கெட்',
  cup: 'கப்',

  // Auth & profile
  'Welcome back to your kitchen': 'வாங்க, உங்க கிச்சனுக்கு வெல்கம் பேக்!',
  'Set up your kitchen': 'உங்க கிச்சனை செட் பண்ணலாம் வாங்க',
  'Your name': 'உங்க பேர்',
  'Kitchen name (optional)': 'கிச்சன் பேர் (தேவைப்பட்டா)',
  "e.g. Amma's Kitchen": 'உதா. அம்மா கிச்சன்',
  'Create account': 'அக்கவுண்ட் உருவாக்கு',
  'Log in': 'லாகின்',
  'Already have an account?': 'ஏற்கனவே அக்கவுண்ட் இருக்கா?',
  'New here?': 'புதுசா வந்திருக்கீங்களா?',
  'Create an account': 'அக்கவுண்ட் உருவாக்குங்க',
  'Kitchen name': 'கிச்சன் பேர்',
  'Change password': 'பாஸ்வேர்ட் மாத்து',
  'Current password': 'இப்போ இருக்குற பாஸ்வேர்ட்',
  'New password': 'புது பாஸ்வேர்ட்',
  'Profile saved.': 'ப்ரொஃபைல் சேவ் ஆயிடுச்சு.',
  'Log out': 'லாக்அவுட்',
  'Opening your kitchen…': 'உங்க கிச்சனை திறக்குது…',

  // Home
  'Good morning': 'காலை வணக்கம்',
  'Good afternoon': 'மதிய வணக்கம்',
  'Good evening': 'மாலை வணக்கம்',
  'Checking your kitchen…': 'உங்க கிச்சனை செக் பண்ணுது…',
  'Start by stocking your kitchen': 'முதல்ல வீட்டுல இருக்குற சாமான்களை சேருங்க',
  'Add what you have at home and we’ll show what you can cook.': 'வீட்டுல என்ன இருக்குன்னு சேர்த்தீங்கன்னா, என்ன சமைக்கலாம்னு நாங்க சொல்றோம்.',
  'Today’s meals': 'இன்னைக்கு சாப்பாடு',
  'Nothing planned for today.': 'இன்னைக்கு எதுவும் பிளான் பண்ணல.',
  Cooked: 'சமைச்சாச்சு',
  Ready: 'ரெடி',
  'Missing items': 'சாமான் குறையுது',
  'What can I cook now?': 'இப்போ என்ன சமைக்கலாம்?',
  'Nothing fully ready — {n} recipe(s) almost there.': 'முழுசா ரெடியானது இல்ல — {n} ரெசிபி கிட்டத்தட்ட ரெடி.',
  'Add more to your kitchen to unlock recipes.': 'இன்னும் சாமான் சேர்த்தா நிறைய ரெசிபி பண்ணலாம்.',
  'See all': 'எல்லாம் பாருங்க',
  'Use soon': 'சீக்கிரம் யூஸ் பண்ணுங்க',
  'Expires today': 'இன்னைக்கு எக்ஸ்பைரி',
  'Expires tomorrow': 'நாளைக்கு எக்ஸ்பைரி',
  'Expires in {n} days': 'இன்னும் {n} நாள்ல எக்ஸ்பைரி',
  '{n} item(s) have expired.': '{n} சாமான் எக்ஸ்பைரி ஆயிடுச்சு.',
  'Cook these first': 'இதை முதல்ல சமைங்க',
  'Low stock': 'ஸ்டாக் கம்மி',
  'Groceries to buy': 'வாங்க வேண்டிய மளிகை',

  // Kitchen
  Speak: 'பேசுங்க',
  'Add by voice': 'பேசியே சேருங்க',
  Expired: 'எக்ஸ்பைரி ஆயிடுச்சு',
  'Your kitchen is empty': 'கிச்சன் காலியா இருக்கு',
  'Add what you have at home to see what you can cook.': 'வீட்டுல இருக்குற சாமான்களை சேருங்க, என்ன சமைக்கலாம்னு பாக்கலாம்.',
  'Nothing running low': 'எதுவும் கம்மியா இல்ல',
  'Set a minimum stock on items to get reminders here.': 'ஒவ்வொரு சாமானுக்கும் "குறைஞ்சபட்ச ஸ்டாக்" வெச்சா, தீரும்போது இங்கே ஞாபகப்படுத்துவோம்.',
  'Nothing expiring soon': 'சீக்கிரம் எக்ஸ்பைரி ஆகுறது எதுவும் இல்ல',
  'Items expiring in the next 3 days show up here.': 'அடுத்த 3 நாள்ல எக்ஸ்பைரி ஆகுற சாமான்கள் இங்கே வரும்.',
  'No expired items': 'எக்ஸ்பைரி ஆனது எதுவும் இல்ல',
  'Nice — nothing has gone past its date.': 'சூப்பர் — எதுவும் எக்ஸ்பைரி ஆகல.',
  'Write off all expired stock': 'எக்ஸ்பைரி ஆனதெல்லாம் எடுத்துடு',
  'Write off all expired stock? This records it as expired and sets those items to zero.': 'எக்ஸ்பைரி ஆனதெல்லாம் எடுத்துடலாமா? அதெல்லாம் ஸ்டாக்ல ஜீரோ ஆயிடும்.',
  'Writing off…': 'எடுக்குது…',
  'Checking your shelves…': 'அலமாரியை செக் பண்ணுது…',
  'Add to kitchen': 'கிச்சன்ல சேர்',
  'Add {name}': '{name} சேர்',
  '{name} added to your kitchen.': '{name} கிச்சன்ல சேர்ந்தாச்சு.',
  'Search ingredient': 'சாமான் தேடுங்க',
  'e.g. tomato': 'உதா. தக்காளி',
  'No match. Add “{name}” as a new ingredient:': 'கிடைக்கல. “{name}”-ஐ புது சாமானா சேர்க்கலாம்:',
  Category: 'வகை',
  'Choose…': 'தேர்ந்தெடுங்க…',
  'Pick the unit you usually measure it in.': 'வழக்கமா எந்த அளவுல வாங்குவீங்களோ அதை தேர்ந்தெடுங்க.',
  Quantity: 'அளவு',
  Unit: 'யூனிட்',
  'Expiry date (optional)': 'எக்ஸ்பைரி தேதி (தேவைப்பட்டா)',
  'Expiry date': 'எக்ஸ்பைரி தேதி',
  'Min. stock (optional)': 'குறைஞ்சபட்ச ஸ்டாக் (தேவைப்பட்டா)',
  'Min. stock ({unit})': 'குறைஞ்சபட்ச ஸ்டாக் ({unit})',
  'Stored in': 'எங்க வெச்சிருக்கீங்க',
  Item: 'சாமான்',
  Discard: 'தூக்கிப் போடு',
  'Set count': 'சரியான அளவு',
  Bought: 'வாங்கினது',
  Added: 'சேர்த்தது',
  'Stock count': 'ஸ்டாக் சரிபார்ப்பு',
  Discarded: 'தூக்கிப் போட்டது',
  '{n} days left': 'இன்னும் {n} நாள்',
  'Stock updated.': 'ஸ்டாக் அப்டேட் ஆயிடுச்சு.',
  'Details saved.': 'விவரம் சேவ் ஆயிடுச்சு.',
  'Remove {name} from your kitchen?': '{name}-ஐ கிச்சன்லேர்ந்து எடுத்துடலாமா?',
  '{name} removed.': '{name} எடுத்தாச்சு.',
  'Actual amount now': 'இப்போ உண்மையா எவ்வளவு இருக்கு',
  'Note (optional)': 'குறிப்பு (தேவைப்பட்டா)',
  'Update stock': 'ஸ்டாக் அப்டேட் பண்ணு',
  Details: 'விவரம்',
  'Save details': 'விவரம் சேவ் பண்ணு',
  History: 'ஹிஸ்டரி',
  'No stock changes yet.': 'ஸ்டாக்ல இன்னும் எந்த மாற்றமும் இல்ல.',
  'Remove from kitchen': 'கிச்சன்லேர்ந்து எடுத்துடு',

  // Cook / recipes
  'What can I cook?': 'என்ன சமைக்கலாம்?',
  'All recipes': 'எல்லா ரெசிபியும்',
  'Available now': 'இப்போவே பண்ணலாம்',
  Almost: 'கிட்டத்தட்ட',
  'Any meal': 'எந்த நேரமும்',
  'Under 30 min': '30 நிமிஷத்துக்குள்',
  '💪 High protein': '💪 நிறைய புரோட்டீன்',
  '🥗 Low calorie': '🥗 கம்மி கலோரி',
  '🌾 High fiber': '🌾 நிறைய நார்ச்சத்து',
  'No recipes match': 'பொருந்துற ரெசிபி இல்ல',
  'Try a different meal or time filter.': 'வேற நேரம் இல்லன்னா வேற ஃபில்டர் ட்ரை பண்ணுங்க.',
  'Nothing fully ready yet': 'இன்னும் முழுசா ரெடியானது இல்ல',
  'Check “Almost” — you may be just an ingredient or two away.': '“கிட்டத்தட்ட” பாருங்க — ஒன்னு ரெண்டு சாமான்தான் குறையலாம்.',
  'No near misses': 'கிட்டத்தட்ட ரெடியானது எதுவும் இல்ல',
  'Nothing needs using up': 'சீக்கிரம் யூஸ் பண்ண வேண்டியது எதுவும் இல்ல',
  'Recipes using items that expire within 3 days show up here.': '3 நாள்ல எக்ஸ்பைரி ஆகுற சாமானை யூஸ் பண்ற ரெசிபிகள் இங்கே வரும்.',
  'Use soon: {name} ({when})': 'சீக்கிரம் யூஸ் பண்ணுங்க: {name} ({when})',
  '{n}d': '{n} நாள்',
  'You have everything': 'எல்லாமே இருக்கு',
  'Need {items}': 'வேணும்: {items}',
  '+{n} more': 'இன்னும் {n}',
  'Your kitchen is empty, so every recipe shows 0%.': 'கிச்சன் காலியா இருக்கறதால எல்லா ரெசிபியும் 0% காட்டுது.',
  'Add what you have': 'இருக்குறதை சேருங்க',
  '{n} min': '{n} நிமி',
  Recipes: 'ரெசிபிகள்',
  Say: 'சொல்லுங்க',
  'Search recipes…': 'ரெசிபி தேடுங்க…',
  Veg: 'சைவம்',
  'Non-veg': 'அசைவம்',
  'My recipes': 'என் ரெசிபிகள்',
  'Finding recipes…': 'ரெசிபி தேடுது…',
  'No recipes found': 'ரெசிபி எதுவும் கிடைக்கல',
  'Recipes you create will appear here.': 'நீங்க சேர்க்குற ரெசிபிகள் இங்கே வரும்.',
  'Try a different search or filter.': 'வேற மாதிரி தேடிப் பாருங்க.',
  'serves {n}': '{n} பேருக்கு',
  '{n} ingredients': '{n} சாமான்',
  '{n} g protein': '{n} கி புரோட்டீன்',
  'Delete {name}?': '{name}-ஐ டெலீட் பண்ணலாமா?',
  'Opening recipe…': 'ரெசிபி திறக்குது…',
  'Recipe not found.': 'ரெசிபி கிடைக்கல.',
  'Uploading…': 'அப்லோட் ஆகுது…',
  'Change photo': 'போட்டோ மாத்து',
  'Add photo': 'போட்டோ சேர்',
  'Remove photo': 'போட்டோ எடுத்துடு',
  'Prep {n} min': 'ரெடி பண்ண {n} நிமி',
  'Cook {n} min': 'சமைக்க {n} நிமி',
  Ingredients: 'தேவையான சாமான்கள்',
  'Fewer servings': 'ஆள் குறை',
  'More servings': 'ஆள் கூட்டு',
  'Serves {n}': '{n} பேருக்கு',
  'You have everything for this.': 'இதுக்கு வேண்டியதெல்லாம் இருக்கு.',
  'Compared with what’s in your kitchen (expired items excluded).': 'உங்க கிச்சன்ல இருக்குறதோட கம்பேர் பண்ணது (எக்ஸ்பைரி ஆனது தவிர).',
  'Have {have} · need {more} more': '{have} இருக்கு · இன்னும் {more} வேணும்',
  'Not in kitchen': 'கிச்சன்ல இல்ல',
  Method: 'செய்முறை',
  'Cook this · serves {n}': 'இதை சமைங்க · {n} பேருக்கு',
  'Cook for {n}': '{n} பேருக்கு சமைக்க',
  'This will be taken out of your kitchen:': 'கிச்சன்லேர்ந்து இதெல்லாம் குறையும்:',
  'Nothing from your kitchen is used — none of these ingredients are in stock.': 'கிச்சன்லேர்ந்து எதுவும் குறையாது — இந்த சாமான் எதுவும் ஸ்டாக்ல இல்ல.',
  '{n} left': 'மீதி {n}',
  'Not enough in your kitchen:': 'கிச்சன்ல போதுமான அளவு இல்ல:',
  'short {n}': '{n} குறையுது',
  'Only what you have will be deducted — stock never goes below zero.': 'இருக்குறது மட்டும்தான் குறையும் — ஸ்டாக் ஜீரோவுக்கு கீழே போகாது.',
  'Confirm — I cooked this': 'ஆமா — இதை சமைச்சேன்',

  // Recipe form
  'Edit recipe': 'ரெசிபி மாத்து',
  'Check your recipe': 'உங்க ரெசிபியை பாருங்க',
  'New recipe': 'புது ரெசிபி',
  'Drafted by AI from what you said. Check the amounts, pick any highlighted ingredients, then save.': 'நீங்க சொன்னதை வெச்சு AI எழுதிச்சு. அளவுகளை பாருங்க, மஞ்சள்ல இருக்குற சாமான்களை தேர்ந்தெடுங்க, அப்புறம் சேவ் பண்ணுங்க.',
  'Estimated {kcal} kcal and {protein} g protein per serving.': 'ஒருத்தருக்கு சுமார் {kcal} கலோரி, {protein} கி புரோட்டீன்.',
  'Short description': 'சின்ன விளக்கம்',
  Meal: 'எந்த நேரம்',
  Cuisine: 'சமையல் வகை',
  'e.g. South Indian': 'உதா. தென்னிந்திய',
  Serves: 'எத்தனை பேருக்கு',
  'Prep min': 'ரெடி பண்ண நிமி',
  'Cook min': 'சமைக்க நிமி',
  'AI heard “{heard}”': 'AI கேட்டது “{heard}”',
  'check this is the right ingredient and amount.': 'சரியான சாமானும் அளவும்தானான்னு பாருங்க.',
  'pick the closest ingredient or remove this row.': 'கிட்டத்தட்ட பொருந்துற சாமானை தேர்ந்தெடுங்க, இல்லன்னா இந்த வரியை எடுத்துடுங்க.',
  'Ingredient {n}': 'சாமான் {n}',
  'Add ingredient': 'சாமான் சேர்',
  'One step per line.': 'ஒரு வரிக்கு ஒரு ஸ்டெப்.',
  'Save recipe': 'ரெசிபி சேவ் பண்ணு',
  'Create recipe': 'ரெசிபி சேர்',
  "Built-in recipes can't be edited.": 'ஆப்ல இருக்குற ரெசிபிகளை மாத்த முடியாது.',

  // Planner
  'Meal planner': 'சாப்பாடு பிளான்',
  'AI plan': 'AI பிளான்',
  'Previous week': 'போன வாரம்',
  'Next week': 'அடுத்த வாரம்',
  'Loading your week…': 'உங்க வாரம் லோட் ஆகுது…',
  'Add {meal} on {date}': '{date} அன்னைக்கு {meal} சேர்',
  'Planned meal': 'பிளான் பண்ண சாப்பாடு',
  'Plan a meal': 'சாப்பாடு பிளான் பண்ணு',
  'No recipes match.': 'பொருந்துற ரெசிபி இல்ல.',
  Servings: 'எத்தனை பேருக்கு',
  'Add to plan': 'பிளான்ல சேர்',
  'View recipe': 'ரெசிபி பாரு',
  'Open & cook': 'திறந்து சமை',

  // Groceries
  'Loading your list…': 'லிஸ்ட் லோட் ஆகுது…',
  'Could not load groceries.': 'மளிகை லிஸ்ட் லோட் ஆகல.',
  'List updated from your meal plan for the next 7 days.': 'அடுத்த 7 நாள் பிளானை வெச்சு லிஸ்ட் அப்டேட் ஆயிடுச்சு.',
  'Cleared purchased items.': 'வாங்கினதெல்லாம் லிஸ்ட்லேர்ந்து எடுத்தாச்சு.',
  'Calculating…': 'கணக்கு போடுது…',
  'Update from meal plan': 'பிளானை வெச்சு லிஸ்ட் போடு',
  'Last calculated for {from} – {to}. Recalculate for the next 7 days.': 'கடைசியா {from} – {to} வரைக்கும் கணக்கு போட்டது. அடுத்த 7 நாளுக்கு திரும்ப போடுங்க.',
  'Adds what your planned meals for the next 7 days need, minus what’s in your kitchen.': 'அடுத்த 7 நாள் சாப்பாட்டுக்கு என்ன வேணுமோ, கிச்சன்ல இருக்குறதை கழிச்சு லிஸ்ட் போடும்.',
  'Add {n} purchased food item(s) to your kitchen?': 'வாங்கின {n} சாமானை கிச்சன்ல சேர்க்கலாமா?',
  'Add item, e.g. Soap': 'சாமான் சேருங்க, உதா. சோப்பு',
  'Your list is empty': 'லிஸ்ட் காலியா இருக்கு',
  'Plan some meals, then tap “Update from meal plan” — or add items yourself.': 'கொஞ்சம் சாப்பாடு பிளான் பண்ணிட்டு “பிளானை வெச்சு லிஸ்ட் போடு” தட்டுங்க — இல்லன்னா நீங்களே சாமான் சேருங்க.',
  'Unmark {name}': '{name} டிக் எடுத்துடு',
  'Mark {name} purchased': '{name} வாங்கியாச்சுன்னு டிக் பண்ணு',
  'in kitchen': 'கிச்சன்ல இருக்கு',
  'Clear purchased items': 'வாங்கினதை லிஸ்ட்லேர்ந்து எடுத்துடு',
  'Added to your kitchen.': 'கிச்சன்ல சேர்ந்தாச்சு.',
  'Already added to your kitchen.': 'ஏற்கனவே கிச்சன்ல சேர்ந்தாச்சு.',
  Need: 'வேணும்',
  'Price (₹)': 'விலை (₹)',
  'Remove from list': 'லிஸ்ட்லேர்ந்து எடுத்துடு',
  'Add to kitchen?': 'கிச்சன்ல சேர்க்கலாமா?',
  'Skipped (no quantity entered): {names}. Tap them in the list to add how much you bought.': 'அளவு போடாததால விட்டது: {names}. எவ்வளவு வாங்கினீங்கன்னு லிஸ்ட்ல தட்டி போடுங்க.',
  'Add {n} item(s) to kitchen': '{n} சாமானை கிச்சன்ல சேர்',

  // Health
  'High protein': 'நிறைய புரோட்டீன்',
  'Low calorie': 'கம்மி கலோரி',
  'High fiber': 'நிறைய நார்ச்சத்து',
  Protein: 'புரோட்டீன்',
  Carbs: 'கார்ப்ஸ்',
  Fat: 'கொழுப்பு',
  Fiber: 'நார்ச்சத்து',
  Nutrition: 'சத்து விவரம்',
  'per serving · estimated': 'ஒருத்தருக்கு · தோராயமா',
  'Macronutrients in grams per serving': 'ஒருத்தருக்கான சத்துகள் (கிராம்ல)',
  '{label}: {n} g per serving': '{label}: ஒருத்தருக்கு {n} கி',
  'No nutrition estimate yet.': 'இன்னும் சத்து கணக்கு போடல.',
  'Estimating…': 'கணக்கு போடுது…',
  'Re-estimate with AI': 'AI-ல திரும்ப கணக்கு போடு',
  'Estimate with AI': 'AI-ல கணக்கு போடு',
  'Protein per person': 'ஒருத்தருக்கு புரோட்டீன்',
  'Show chart': 'சார்ட் காட்டு',
  'Show table': 'டேபிள் காட்டு',
  'Grams per day from planned meals (one serving of each dish). Line = {n} g goal.': 'பிளான் பண்ண சாப்பாட்டுல ஒரு நாளைக்கு எத்தனை கிராம் (ஒவ்வொரு டிஷ்ஷும் ஒருத்தருக்கு). கோடு = {n} கி டார்கெட்.',
  Day: 'நாள்',
  '{n} g goal': '{n} கி டார்கெட்',
  '{n} dish(es) without estimate': '{n} டிஷ்ஷுக்கு கணக்கு இல்ல',

  // AI mode
  Assistant: 'அசிஸ்டன்ட்',
  'AI mode': 'AI மோட்',
  'Talk to your kitchen. The AI only prepares drafts — you always check before anything is saved.': 'உங்க கிச்சன்கிட்ட பேசுங்க. AI ஒரு டிராஃப்ட் மட்டும்தான் ரெடி பண்ணும் — சேவ் பண்றதுக்கு முன்னாடி நீங்க பாத்துக்கலாம்.',
  'Say what you bought': 'என்ன வாங்கினீங்கன்னு சொல்லுங்க',
  '“1 kg chicken, a dozen eggs and 2 litres milk” → added to your kitchen after you check it.': '“1 கிலோ சிக்கன், ஒரு டஜன் முட்டை, 2 லிட்டர் பால்” → நீங்க பாத்ததும் கிச்சன்ல சேர்ந்துடும்.',
  'Say a recipe': 'ரெசிபி சொல்லுங்க',
  'Dictate a recipe in English or Tamil → a ready-to-save recipe with estimated nutrition.': 'தமிழ்லயோ இங்கிலீஷ்லயோ ரெசிபி சொல்லுங்க → சத்து கணக்கோட ரெடியான ரெசிபி.',
  'Plan my meals': 'என் சாப்பாடு பிளான் பண்ணு',
  'Balanced, high-protein or lighter days, picked from your recipes and what’s in your kitchen.': 'பேலன்ஸ்டா, நிறைய புரோட்டீனா, இல்ல லைட்டா — உங்க ரெசிபியும் கிச்சன்ல இருக்குறதும் வெச்சு.',
  'Runs on a free AI model. Voice uses your browser’s speech recognition (Chrome/Edge/Android).': 'இலவச AI-ல ஓடுது. பேச்சுக்கு உங்க போன்/பிரவுசர்ல இருக்குற வாய்ஸ் வசதியை யூஸ் பண்ணுது.',
  'This can take a few seconds — please keep this open.': 'சில நொடி ஆகலாம் — இதை மூடாதீங்க.',
  'Not in your ingredient list — pick one': 'லிஸ்ட்ல இல்ல — ஒன்னை தேர்ந்தெடுங்க',
  'How much?': 'எவ்வளவு?',
  'Check the unit': 'யூனிட்டை பாருங்க',
  'Best guess — check it': 'ஊகம்தான் — ஒரு தடவை பாருங்க',
  'e.g. I bought 1 kg chicken, a dozen eggs and 2 litres of milk': 'உதா. 1 கிலோ சிக்கன், ஒரு டஜன் முட்டை, 2 லிட்டர் பால் வாங்கினேன்',
  'Understanding…': 'புரிஞ்சுக்குது…',
  Understand: 'புரிஞ்சுக்கோ',
  'Check and fix before adding.': 'சேர்க்கறதுக்கு முன்னாடி பாத்து சரி பண்ணுங்க.',
  'Read instantly (no AI needed).': 'உடனே புரிஞ்சுடுச்சு (AI தேவைப்படல).',
  'Understood by AI.': 'AI புரிஞ்சுக்கிச்சு.',
  'Choose ingredient…': 'சாமானை தேர்ந்தெடுங்க…',
  'Heard “{heard}”': 'கேட்டது “{heard}”',
  'I bought these': 'இதெல்லாம் வாங்கினேன்',
  'Just add to stock': 'ஸ்டாக்ல மட்டும் சேர்',
  'Say it again': 'திரும்ப சொல்லுங்க',
  'e.g. Egg curry for 4. Boil 6 eggs. Fry 2 onions and 2 tomatoes in 2 tablespoons oil with 1 teaspoon chilli powder…': 'உதா. 4 பேருக்கு முட்டை குழம்பு. 6 முட்டை வேக வைங்க. 2 ஸ்பூன் எண்ணெய்ல 2 வெங்காயம், 2 தக்காளி, 1 டீஸ்பூன் மிளகாய்த்தூள் போட்டு வதக்குங்க…',
  'Say the name, how many it serves, ingredients with amounts, and the steps. You’ll review everything before saving.': 'பேரு, எத்தனை பேருக்கு, சாமான் அளவோட, எப்படி செய்யணும் — இதெல்லாம் சொல்லுங்க. சேவ் பண்றதுக்கு முன்னாடி பாத்துக்கலாம்.',
  'Writing your recipe…': 'உங்க ரெசிபி எழுதுது…',
  'Create recipe draft': 'ரெசிபி டிராஃப்ட் ரெடி பண்ணு',
  '⚖️ Balanced': '⚖️ பேலன்ஸ்டு',
  '🥗 Lighter': '🥗 லைட்டா',
  'The AI couldn’t make a plan this time. Please try again.': 'இந்த தடவை AI-ஆல பிளான் போட முடியல. திரும்ப ட்ரை பண்ணுங்க.',
  'AI meal plan': 'AI சாப்பாடு பிளான்',
  Starting: 'எப்போலேர்ந்து',
  Days: 'எத்தனை நாள்',
  Meals: 'எந்த நேரம்',
  Goal: 'டார்கெட்',
  People: 'எத்தனை பேர்',
  'Planning your meals…': 'உங்க சாப்பாடு பிளான் போடுது…',
  'Suggest a plan': 'பிளான் போட்டுக் காட்டு',
  'Chosen from your recipes, favouring what’s in your kitchen and items expiring soon. Nothing is saved until you add it.': 'உங்க ரெசிபிகள்லேர்ந்து, கிச்சன்ல இருக்குறதுக்கும் சீக்கிரம் எக்ஸ்பைரி ஆகுறதுக்கும் முன்னுரிமை குடுத்து எடுத்தது. நீங்க சேர்க்குற வரைக்கும் எதுவும் சேவ் ஆகாது.',
  'Add {n} meals to planner': '{n} சாப்பாட்டை பிளான்ல சேர்',
  'Try different options': 'வேற ஆப்ஷன் ட்ரை பண்ணுங்க',

  // Voice
  'Microphone permission was denied.': 'மைக் பர்மிஷன் குடுக்கல.',
  'Voice input stopped ({error}).': 'வாய்ஸ் நின்னுடுச்சு ({error}).',
  'Stop listening': 'நிறுத்து',
  'Listening… tap ■ when done': 'கேக்குது… முடிஞ்சதும் ■ தட்டுங்க',
  'Tap 🎙️ and speak, or type': '🎙️ தட்டி பேசுங்க, இல்லன்னா டைப் பண்ணுங்க',
  'Voice input isn’t supported in this browser — type instead (Chrome or Edge support voice).': 'இந்த பிரவுசர்ல வாய்ஸ் வேலை செய்யாது — டைப் பண்ணுங்க (Chrome, Edge-ல வாய்ஸ் வேலை செய்யும்).',

  // Smart plan
  'Smart meal plan': 'ஸ்மார்ட் சாப்பாடு பிளான்',
  'Smart plan': 'ஸ்மார்ட் பிளான்',
  'Shuffle': 'வேற மாதிரி',
  'No recipes fit these meals yet. Add a few recipes and try again.': 'இந்த நேரத்துக்கு பொருந்துற ரெசிபி இன்னும் இல்ல. சில ரெசிபி சேர்த்துட்டு ட்ரை பண்ணுங்க.',
  'Picked from your recipes for your goal — no dish twice within 3 days, no two similar dishes on one day, favouring what’s in your kitchen. Nothing is saved until you add it.': 'உங்க டார்கெட்டுக்கு ஏத்த மாதிரி உங்க ரெசிபிகள்லேர்ந்து எடுத்தது — 3 நாளுக்குள்ள ஒரே டிஷ் திரும்ப வராது, ஒரே நாள்ல ஒரே மாதிரி டிஷ் வராது, கிச்சன்ல இருக்குறதுக்கு முன்னுரிமை. நீங்க சேர்க்குற வரைக்கும் எதுவும் சேவ் ஆகாது.',
  'protein per person / day': 'ஒருத்தருக்கு / ஒரு நாளைக்கு புரோட்டீன்',
  'kcal per person / day': 'ஒருத்தருக்கு / ஒரு நாளைக்கு கலோரி',
  'Balanced, high-protein or lighter days from your recipes — no look-alike dishes on one day.': 'பேலன்ஸ்டா, நிறைய புரோட்டீனா, இல்ல லைட்டா — ஒரே நாள்ல ஒரே மாதிரி டிஷ் வராது.',

  // Clear week
  'Clear this week': 'இந்த வாரத்தை க்ளியர் பண்ணு',
  'Clearing…': 'க்ளியர் ஆகுது…',
  'Remove all {n} planned meals from this week? Meals already cooked are kept.': 'இந்த வாரம் பிளான் பண்ண {n} சாப்பாட்டையும் எடுத்துடலாமா? ஏற்கனவே சமைச்சது அப்படியே இருக்கும்.',

  // Diet
  'Food preference': 'சாப்பாடு விருப்பம்',
  Any: 'எதுவானாலும்',
  '🟢 Veg only': '🟢 சைவம் மட்டும்',
  '🔴 Non-veg': '🔴 அசைவம்',

  // Google
  or: 'இல்லன்னா',
  'Continue with Google': 'Google-ல தொடருங்க',
  'A4 landscape · Choose a printer, or “Save as PDF”.': 'A4 படுக்கை வசம் · பிரிண்டரை தேர்ந்தெடுங்க, இல்லன்னா “Save as PDF”.',

  // Password field
  'Show password': 'பாஸ்வேர்ட் காட்டு',
  'Hide password': 'பாஸ்வேர்ட் மறை',

  // Printable plan
  'Print / PDF': 'பிரிண்ட் / PDF',
  'Preparing your plan…': 'உங்க பிளான் ரெடி ஆகுது…',
  'Could not load the plan.': 'பிளான் லோட் ஆகல.',
  'Back to planner': 'பிளானுக்கு திரும்பு',
  'A4 landscape · In the print window choose “Save as PDF” to download.': 'A4 படுக்கை வசம் · டவுன்லோட் பண்ண, பிரிண்ட் விண்டோல “Save as PDF” தேர்ந்தெடுங்க.',
  'Print': 'பிரிண்ட்',
  'Save as PDF': 'PDF-ஆ சேவ் பண்ணு',
  'Weekly meal plan': 'இந்த வார சாப்பாடு பிளான்',
  'Calories per person': 'ஒருத்தருக்கு கலோரி',
  '{n} kcal guide': '{n} கலோரி அளவு',
  '{n} meals planned · per-person values assume one serving of each dish · nutrition is estimated': '{n} சாப்பாடு பிளான் பண்ணியாச்சு · ஒருத்தருக்கு ஒரு பங்குன்னு கணக்கு · சத்து தோராயமானது',
  'Printed from Adupangarai': 'அடுப்பங்கரை ஆப்லேர்ந்து பிரிண்ட் பண்ணது',

  // Health coach
  Coach: 'கோச்',
  '🎯 My target': '🎯 என் டார்கெட்',
  'Fits each day to your Coach calorie target (one serving per person).': 'ஒவ்வொரு நாளும் உங்க கோச் கலோரி டார்கெட்டுக்கு ஏத்த மாதிரி (ஒருத்தருக்கு ஒரு சர்விங்).',
  'kcal per person / day (target {n})': 'kcal ஒருத்தருக்கு / நாளுக்கு (டார்கெட் {n})',
  Started: 'ஆரம்பிச்சாச்சு',
  'Set your goal': 'கோல் செட் பண்ணுங்க',
  'First log': 'முதல் பதிவு',
  'Log your first meal': 'முதல் சாப்பாட்டை போடுங்க',
  'Plan follower': 'பிளான் ஃபாலோயர்',
  'Eat every planned meal in a day, on target': 'ஒரு நாள் பிளான் பண்ண எல்லா சாப்பாடும், டார்கெட்குள்ள',
  'Plan pro': 'பிளான் ப்ரோ',
  'Follow the plan 3 days in a row': 'தொடர்ந்து 3 நாள் பிளான் ஃபாலோ பண்ணுங்க',
  'On target': 'டார்கெட்ல',
  '3 days in a row on target': 'தொடர்ந்து 3 நாள் டார்கெட்ல',
  'Week warrior': 'வீக் வாரியர்',
  '7 days in a row on target': 'தொடர்ந்து 7 நாள் டார்கெட்ல',
  'Habit hero': 'பழக்க ஹீரோ',
  '21 days in a row on target': 'தொடர்ந்து 21 நாள் டார்கெட்ல',
  'Step goal': 'ஸ்டெப் கோல்',
  'Reach your step goal': 'ஸ்டெப் கோலை அடிங்க',
  Walker: 'வாக்கர்',
  'Step goal 7 days in a row': 'தொடர்ந்து 7 நாள் ஸ்டெப் கோல்',
  '100K club': '100K கிளப்',
  '100,000 steps in total': 'மொத்தம் 1,00,000 ஸ்டெப்ஸ்',
  'Protein pro': 'புரோட்டீன் ப்ரோ',
  'Hit your protein target on 5 days': '5 நாள் புரோட்டீன் டார்கெட் அடிங்க',
  'Honest eater': 'நேர்மையான சாப்பாட்டுக்காரர்',
  'Log extra food 5 times': 'எக்ஸ்ட்ரா சாப்பிட்டதை 5 தடவை போடுங்க',
  'First kg': 'முதல் கிலோ',
  '1 kg towards your goal': 'கோல் பக்கம் 1 கிலோ',
  Halfway: 'பாதி தூரம்',
  'Halfway to your target weight': 'டார்கெட் வெயிட்டுக்கு பாதி வந்தாச்சு',
  'Goal reached': 'கோல் அடிச்சாச்சு',
  'Reach your target weight': 'டார்கெட் வெயிட்டை அடிங்க',
  'Lose weight': 'வெயிட் குறைக்க',
  'Stay fit': 'ஃபிட்டா இருக்க',
  'Gain weight': 'வெயிட் ஏத்த',
  'Mostly sitting': 'பெரும்பாலும் உட்கார்ந்து',
  'Desk work, little walking': 'டெஸ்க் வேலை, கொஞ்சம் தான் நடை',
  'Lightly active': 'கொஞ்சம் ஆக்டிவ்',
  'Housework, walks 1–3 days a week': 'வீட்டு வேலை, வாரத்துல 1–3 நாள் வாக்',
  Active: 'ஆக்டிவ்',
  'Exercise 3–5 days a week': 'வாரத்துல 3–5 நாள் எக்சர்சைஸ்',
  'Very active': 'ரொம்ப ஆக்டிவ்',
  'Hard exercise or physical work most days': 'பெரும்பாலான நாள் கடுமையான எக்சர்சைஸ் இல்லன்னா உடல் உழைப்பு',
  Gentle: 'மெதுவா',
  Steady: 'சீரா',
  Faster: 'வேகமா',
  'Your goal': 'உங்க கோல்',
  Woman: 'பெண்',
  Man: 'ஆண்',
  'Birth year': 'பிறந்த வருஷம்',
  'Height (cm)': 'உயரம் (cm)',
  'Weight (kg)': 'வெயிட் (kg)',
  'Target weight (kg)': 'டார்கெட் வெயிட் (kg)',
  'A healthy weight for your height is about {from}–{to} kg.': 'உங்க உயரத்துக்கு ஹெல்தியான வெயிட் சுமார் {from}–{to} kg.',
  Pace: 'வேகம்',
  '{kg} kg / week': 'வாரத்துக்கு {kg} kg',
  'How active are you?': 'நீங்க எவ்ளோ ஆக்டிவ்?',
  'Daily step goal': 'தினசரி ஸ்டெப் கோல்',
  'General guidance, not medical advice. If you are pregnant, diabetic or have a health condition, please check with your doctor first.': 'இது பொதுவான வழிகாட்டல் தான், மருத்துவ ஆலோசனை இல்ல. கர்ப்பமா இருந்தா, சுகர் இல்லன்னா வேற உடல்நல பிரச்சனை இருந்தா, முதல்ல டாக்டர்கிட்ட கேளுங்க.',
  'Save goal': 'கோல் சேவ் பண்ணு',
  'Start my challenge': 'என் சேலஞ்ச் ஆரம்பி',
  'Ate something extra?': 'எக்ஸ்ட்ரா ஏதாவது சாப்பிட்டீங்களா?',
  'No judgement — every honest log helps your coach help you. 🙂': 'யாரும் ஜட்ஜ் பண்ண மாட்டாங்க — உண்மையா போட்டா தான் கோச் உங்களுக்கு ஹெல்ப் பண்ண முடியும். 🙂',
  'Or just say it': 'இல்லன்னா சொல்லுங்க',
  'e.g. 2 vadai and a filter coffee': 'உதா: 2 வடை, ஒரு ஃபில்டர் காபி',
  'Counting calories…': 'கலோரி கணக்கு போடறேன்…',
  'Estimate calories': 'கலோரி கணக்கு போடு',
  Food: 'சாப்பாடு',
  'Type it myself': 'நானே டைப் பண்றேன்',
  'Log {n} kcal': '{n} kcal போடு',
  'Today’s weight': 'இன்னைக்கு வெயிட்',
  'Tip: weigh yourself in the morning, before breakfast, once or twice a week. Daily ups and downs are just water.': 'டிப்: வாரத்துக்கு ஒண்ணு ரெண்டு தடவை, காலைல டிபனுக்கு முன்னாடி வெயிட் பாருங்க. தினம் ஏறி இறங்குறது வெறும் தண்ணி தான்.',
  'Opening your coach…': 'கோச்சை திறக்கறேன்…',
  'Edit your goal': 'கோலை மாத்துங்க',
  'Your health coach': 'உங்க ஹெல்த் கோச்',
  'Set a goal and I’ll give you a daily calorie target, plan meals to it, cheer you on and hand out badges. 🏅': 'கோல் செட் பண்ணுங்க — தினசரி கலோரி டார்கெட் தருவேன், அதுக்கு ஏத்த சாப்பாடு பிளான் பண்ணுவேன், உற்சாகப்படுத்துவேன், பேட்ஜ் தருவேன். 🏅',
  'Stay fit at {kg} kg': '{kg} kg-ல ஃபிட்டா இருக்க',
  'Lose weight · {from} → {to} kg': 'வெயிட் குறைக்க · {from} → {to} kg',
  'Gain weight · {from} → {to} kg': 'வெயிட் ஏத்த · {from} → {to} kg',
  'Previous day': 'முந்தின நாள்',
  'Next day': 'அடுத்த நாள்',
  'Edit goal': 'கோல் மாத்து',
  'Your coach says': 'உங்க கோச் சொல்றது',
  'What I ate': 'நான் சாப்பிட்டது',
  'No meals planned for this day. Add extras below, or plan with “🎯 My target”.': 'இந்த நாளுக்கு சாப்பாடு பிளான் பண்ணல. கீழ எக்ஸ்ட்ரா சேருங்க, இல்லன்னா “🎯 என் டார்கெட்” வெச்சு பிளான் பண்ணுங்க.',
  '{n} kcal per serving': 'ஒரு சர்விங்க்கு {n} kcal',
  'Calories not estimated yet': 'கலோரி இன்னும் கணக்கு போடல',
  'Ate it': 'சாப்பிட்டாச்சு',
  'Ate it?': 'சாப்பிட்டீங்களா?',
  Portion: 'அளவு',
  Extra: 'எக்ஸ்ட்ரா',
  Badges: 'பேட்ஜ்கள்',
  'of {n} kcal': '{n} kcal-ல',
  '{n} kcal left': 'இன்னும் {n} kcal இருக்கு',
  '{n} kcal over': '{n} kcal அதிகம்',
  '{n}-day streak': '{n} நாள் தொடர்ச்சி',
  'Safe minimum': 'பாதுகாப்பான குறைந்தபட்சம்',
  Steps: 'ஸ்டெப்ஸ்',
  '{n} days in a row': 'தொடர்ந்து {n} நாள்',
  Total: 'மொத்தம்',
  'Total steps today': 'இன்னைக்கு மொத்த ஸ்டெப்ஸ்',
  Set: 'செட்',
  'Copy the count from your phone’s step counter (Google Fit, Samsung Health…).': 'உங்க போன் ஸ்டெப் கவுண்டர்லேர்ந்து (Google Fit, Samsung Health…) எண்ணிக்கையை போடுங்க.',
  'Last 7 days': 'கடந்த 7 நாள்',
  'Off target': 'டார்கெட் தவறிச்சு',
  '{n} kcal target': '{n} kcal டார்கெட்',
  'Weight challenge': 'வெயிட் சேலஞ்ச்',
  Weight: 'வெயிட்',
  'Log weight': 'வெயிட் போடு',
  Start: 'ஆரம்பம்',
  Now: 'இப்போ',
  Target: 'டார்கெட்',
  Healthy: 'ஹெல்தி',
  '{kg} kg done · {p}%': '{kg} kg முடிஞ்சது · {p}%',
  'about {n} weeks to go': 'இன்னும் சுமார் {n} வாரம்',
  'Weight trend': 'வெயிட் போக்கு',
  'New badge!': 'புது பேட்ஜ்!',
  'Keep going — tap to close': 'இப்படியே தொடருங்க — மூட டேப் பண்ணுங்க',
  'Set a calorie goal, take the 10k steps challenge and earn badges.': 'கலோரி கோல் செட் பண்ணுங்க, 10k ஸ்டெப்ஸ் சேலஞ்ச் எடுங்க, பேட்ஜ் ஜெயிங்க.',
  Open: 'திற',
  // Account deletion & privacy
  'Delete account': 'அக்கவுன்ட் டெலீட்',
  'This permanently deletes your account, kitchen, recipes, photos, plans, grocery lists and coach data. It cannot be undone.': 'இது உங்க அக்கவுன்ட், கிச்சன், ரெசிபி, போட்டோ, பிளான், மளிகை லிஸ்ட், கோச் டேட்டா எல்லாத்தையும் நிரந்தரமா அழிச்சிடும். திரும்ப கொண்டு வர முடியாது.',
  'Type {email} to confirm': 'உறுதிப்படுத்த {email}-ஐ டைப் பண்ணுங்க',
  'Delete forever': 'நிரந்தரமா டெலீட் பண்ணு',
  'Privacy policy': 'பிரைவசி பாலிசி',
  // Password reset & terms
  'Forgot password?': 'பாஸ்வேர்ட் மறந்துடுச்சா?',
  'Forgot your password?': 'பாஸ்வேர்ட் மறந்துடுச்சா?',
  'Enter your email and we’ll send you a link to set a new one.': 'உங்க இமெயிலை போடுங்க, புது பாஸ்வேர்ட் வைக்க லிங்க் அனுப்பறோம்.',
  'Choose a new password': 'புது பாஸ்வேர்ட் வைங்க',
  'At least 8 characters.': 'குறைஞ்சது 8 எழுத்து.',
  'Send reset link': 'லிங்க் அனுப்பு',
  'Save new password': 'புது பாஸ்வேர்ட் சேவ் பண்ணு',
  'Back to log in': 'லாகினுக்கு திரும்பு',
  'By creating an account you agree to the': 'அக்கவுன்ட் ஆரம்பிச்சா நீங்க ஒத்துக்கறீங்க:',
  'Terms of use': 'யூஸ் பண்ற விதிகள்',
  and: 'மற்றும்',
  // Mobile app
  'This screen is coming in the next update of the app. Meanwhile you can use it on the website.': 'இந்த ஸ்க்ரீன் அடுத்த அப்டேட்ல வரும். அதுவரைக்கும் வெப்சைட்ல யூஸ் பண்ணுங்க.',
  'Open the website': 'வெப்சைட்டை திற',
  'Google sign-in failed. Please try again.': 'Google லாகின் ஆகல. திரும்ப ட்ரை பண்ணுங்க.',
  // From a code comment example; harmless
  '{count} left': 'மீதி {count}',
}

export default ta
